### PR TITLE
Add VITABUILD for cpython 2.7.17

### PR DESCRIPTION
**Pull request by sharkwouter**
I'm still need to do more testing to see how well it works when using it for an application, but it does build and install fine.

### CODE REVIEW

**Comment by sharkwouter** [comment]
To clarify, a VITABUILD allows you to build a library into a package which can be installed in the vita sdk. You can use ``vita-makepkg``to build the packages and use the ``vdpm`` command to install it. That way you can easily install, share and or use this library.

**Comment by sharkwouter** [comment]
Sorry for not taking the time to test this more. Things have been a bit hectic lately, which is unfortunately unlikely to change anytime soon. Would it be better if I convert this from a draft into a formal PR in the meantime? This is a new file after all.

**Comment by uyjulian** [comment]
Sure

**Comment by sharkwouter** [comment]
Okay, done

**Comment by Sulter** [comment]
Any reason for specifically version 2.7.17 instead of the newest python 2: 2.7.18?
I'm building 2.7.18 with no problems.

**Comment by uyjulian** [comment]
I created the patch before python 2.7.18 was released.

**Pull request merged**
